@localURL = http://localhost:3003/api
@preURL = http://114.67.103.78:3003/api
@currentURL = http://localhost:3003/api
###
# @name 交易账户
POST  {{currentURL}}/trade-account
Authorization: test
content-type: application/json

{
    "auto_trade": true,
    "exchange": "huobi",
    "access_key": "a",
    "secret_key": "a",
    "uid": "a",
    "account_id_pro": "a",
    "trade_password": "a"
}
###
# @name 监控的币种
POST  {{currentURL}}/watch-symbol
Authorization: test
content-type: application/json

{
    "symbol": "BTCUSDT"
}


###
# @name 查询交易所交易记录
GET   {{currentURL}}/trade?symbol=BTCUSDT&start=2020-12-19%2015%3A57%3A00:00&end=2020-12-19%2015%3A59%3A00
Authorization: test



###
# @name 下载测试数据
POST   {{currentURL}}/train/download?a=1
Authorization: test
content-type: application/json

{
    "symbol": "btcusdt",
    "period": "5min",
    "size": 800
}

###
# @name 分析数据列表
GET   {{currentURL}}/train/analysis
Authorization: test

###
# @name 分析数据
POST   {{currentURL}}/train/analysis
Authorization: test
content-type: application/json

{
    "url": "http://localhost:3003/download/history-data/btcusdt-5min-2021-02-18.json"
}

###
# @name 自动下单
POST   {{currentURL}}/auto-order-config
Authorization: test
content-type: application/json

{
    "symbol": "btcusdt",
    "buy_usdt": 10,
    "sell_usdt": 10
}
